CREATE INDEX idx_bookings_provider_status ON bookings(provider_id, status);
CREATE INDEX idx_bookings_customer_status ON bookings(customer_id, status);
CREATE INDEX idx_bookings_status_date ON bookings(status, booking_date);
CREATE INDEX idx_bookings_service ON bookings(service_id);
CREATE INDEX idx_bookings_payment_intent ON bookings(payment_intent_id) WHERE payment_intent_id IS NOT NULL;
CREATE INDEX idx_bookings_active ON bookings(provider_id, booking_date DESC) WHERE status IN ('pending', 'confirmed');
CREATE INDEX idx_notifications_inbox ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id, created_at DESC) WHERE read = FALSE OR read IS NULL;
CREATE INDEX idx_messages_thread ON messages(conversation_id, created_at DESC);
CREATE UNIQUE INDEX idx_conversations_pair ON conversations(customer_id, provider_id);
CREATE INDEX idx_conversations_provider ON conversations(provider_id, last_message_at DESC);
CREATE INDEX idx_conversations_customer ON conversations(customer_id, last_message_at DESC);
CREATE INDEX idx_services_provider_active ON services(provider_id, is_active);
CREATE INDEX idx_services_category ON services(category_id) WHERE is_active = TRUE;
CREATE INDEX idx_services_fts ON services USING gin(search_vector);
CREATE INDEX idx_services_tags ON services USING gin(tags);
CREATE INDEX idx_search_de ON search_index USING gin(search_vector_de);
CREATE INDEX idx_search_en ON search_index USING gin(search_vector_en);
CREATE INDEX idx_search_tags ON search_index USING gin(tags);
CREATE INDEX idx_search_active_rating ON search_index(rating DESC, total_bookings DESC) WHERE is_active = TRUE AND can_accept_bookings = TRUE;
CREATE UNIQUE INDEX idx_provider_slug ON provider_profiles(business_slug) WHERE business_slug IS NOT NULL;
CREATE INDEX idx_provider_user ON provider_profiles(user_id);
CREATE INDEX idx_provider_active_rating ON provider_profiles(average_rating DESC) WHERE account_is_active = TRUE AND can_accept_bookings = TRUE;
CREATE INDEX idx_provider_category ON provider_profiles(primary_category_id, average_rating DESC) WHERE account_is_active = TRUE;
CREATE UNIQUE INDEX idx_profiles_url_token ON profiles(url_token) WHERE url_token IS NOT NULL;
CREATE INDEX idx_profiles_stripe ON profiles(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;
CREATE UNIQUE INDEX idx_reviews_booking ON reviews(booking_id);
CREATE INDEX idx_reviews_provider ON reviews(provider_id, created_at DESC);
CREATE INDEX idx_payment_intents_booking ON payment_intents(booking_id);
CREATE UNIQUE INDEX idx_payment_intents_stripe ON payment_intents(stripe_payment_intent_id);
CREATE INDEX idx_payments_booking ON payments(booking_id) WHERE booking_id IS NOT NULL;
CREATE UNIQUE INDEX idx_payments_stripe ON payments(stripe_payment_intent_id) WHERE stripe_payment_intent_id IS NOT NULL;
CREATE INDEX idx_payments_provider ON payments(provider_id, status, created_at DESC) WHERE provider_id IS NOT NULL;
CREATE UNIQUE INDEX idx_invoices_number ON invoices(invoice_number);
CREATE INDEX idx_invoices_booking ON invoices(booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX idx_invoices_provider ON invoices(provider_id, status, created_at DESC);
CREATE INDEX idx_availability_provider_day ON availability_templates(provider_profile_id, day_of_week) WHERE is_active = TRUE OR is_active IS NULL;
CREATE UNIQUE INDEX idx_blocked_pair ON blocked_customers(provider_id, customer_id);
CREATE INDEX idx_quotes_provider ON quotes(provider_id, status);
CREATE INDEX idx_quotes_customer ON quotes(customer_id, status);
CREATE INDEX idx_activity_logs_user ON activity_logs(user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX idx_activity_logs_entity ON activity_logs(entity_id, entity_type) WHERE entity_id IS NOT NULL;
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_cleanup ON refresh_tokens(expires_at) WHERE replaced_by IS NULL;
CREATE INDEX idx_password_resets_user ON password_resets(user_id) WHERE used_at IS NULL;
