CREATE TABLE provider_business_details (
  provider_profile_id UUID PRIMARY KEY
    REFERENCES provider_profiles(id) ON DELETE CASCADE,
  business_tax_number         TEXT,
  business_vat_number         TEXT,
  business_court_registration TEXT,
  is_business_registered      BOOLEAN,
  business_type               TEXT,
  certificates                JSON,
  license_documents           JSON,
  impressum                   TEXT,
  privacy_policy              TEXT,
  terms_conditions            TEXT,
  business_street             TEXT,
  business_house_number       TEXT,
  business_city               TEXT,
  business_postal_code        TEXT,
  address_line2               TEXT,
  owner_first_name            TEXT NOT NULL DEFAULT '',
  owner_last_name             TEXT NOT NULL DEFAULT '',
  owner_date_of_birth         TEXT,
  accepted_provider_terms_at  TIMESTAMPTZ,
  invoice_settings            JSON,
  payout_schedule             TEXT,
  minimum_payout_amount       NUMERIC,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE provider_profiles
  DROP COLUMN IF EXISTS business_tax_number,
  DROP COLUMN IF EXISTS business_vat_number,
  DROP COLUMN IF EXISTS business_court_registration,
  DROP COLUMN IF EXISTS is_business_registered,
  DROP COLUMN IF EXISTS business_type,
  DROP COLUMN IF EXISTS certificates,
  DROP COLUMN IF EXISTS license_documents,
  DROP COLUMN IF EXISTS impressum,
  DROP COLUMN IF EXISTS privacy_policy,
  DROP COLUMN IF EXISTS terms_conditions,
  DROP COLUMN IF EXISTS business_street,
  DROP COLUMN IF EXISTS business_house_number,
  DROP COLUMN IF EXISTS business_city,
  DROP COLUMN IF EXISTS business_postal_code,
  DROP COLUMN IF EXISTS address_line2,
  DROP COLUMN IF EXISTS owner_first_name,
  DROP COLUMN IF EXISTS owner_last_name,
  DROP COLUMN IF EXISTS owner_date_of_birth,
  DROP COLUMN IF EXISTS accepted_provider_terms_at,
  DROP COLUMN IF EXISTS invoice_settings,
  DROP COLUMN IF EXISTS payout_schedule,
  DROP COLUMN IF EXISTS minimum_payout_amount;
